console.log(`SENI SHUNCHAKI SEVARDIM ENDI ESA BU ARMON VA USHALMAS ORZU. MING AFSUS MENING BIR TOMONLAMA SEVGIM , SHUNCHAKI DO‘STDAN HAM BEGONA INSON BO‘LIB QOLDI.
HATO MENI SEVSHNI HAM TASAVVUR QILOMAYDIGON INSONI SEVISH BU BILMADIM NIMAGA TENG LEKIN BU SEVGI EDI SHEKILI`)

//MMM